version: '3.3'

services:
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: matias
      DB_PASSWORD: postgres
      DB_NAME: postgres
      ETHERSCAN_API_KEY: 123
    depends_on:
      - database
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: matias
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_db:/var/lib/postgresql